### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by SamuraiWaffle** [astrayal/ZONE_3_root#1]
I was going to try and download the zone 3 files, but the website is down. Do you have them hosted anywhere else?

**Comment by Lg-PWNd** [comment]
Yes on yandisk.
I can get u a link by tomorrow.
Ill get u a invite to our guide and files for it on the discord server

**Comment by Lg-PWNd** [comment]
@SamuraiWaffle  
Here's a link to invite people to the discord server.
the whole write up plus info needed for PP9 onwards is there. and 
so is links to the needed files.
Please don't mirror, feel free to point to them.

https://discord.gg/TEnCVqf

**Comment by SamuraiWaffle** [comment]
Sweet, thank you for the link!
